[package]
version = "0.1.0"
title = "Piper shelf simulation with newton and isaaclab"
description = "Isaac Lab extension for Piper shelf simulation"
repository = "https://github.com/stickyburn/isaac-projects"

[python.pipapi]
requirements = [
    "isaaclab",
    "isaaclab_newton",
    "numpy>=2",
    "torch>=2.7",
    "gymnasium>=1.2.0",
    "prettytable>=3.3.0",
    "warp-lang>=1.0.0",
    "newton",
    "mujoco>=3.4.0",
    "mujoco-warp",
]

modules = [
    "isaaclab",
    "isaaclab_newton",
    "numpy",
    "torch",
    "gymnasium",
    "prettytable",
    "warp",
    "newton",
    "mujoco",
    "mujoco_warp",
]
